[package]
name = "rust_csp"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_csp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
rand = "0.8"
