[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "rust_csp"
version = "0.1.0"
requires-python = ">=3.10"

[tool.maturin]
module-name = "rust_csp"
features = ["pyo3/extension-module"]
